# Generated by Django 5.0.1 on 2024-02-20 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["cargo", "seat"]},
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("journey", "cargo", "seat")},
        ),
    ]
