# Generated by Django 5.0.1 on 2024-02-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0002_alter_ticket_options_alter_ticket_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journey",
            options={
                "ordering": ["-departure_time"],
                "verbose_name_plural": "journeys",
            },
        ),
        migrations.AlterField(
            model_name="journey",
            name="crews",
            field=models.ManyToManyField(related_name="journeys", to="station.crew"),
        ),
    ]
